### PR TITLE
3 small changes

### PR DESCRIPTION
**Pull request by myMarck**
Small bugfixes and changes that I found using your module

### CODE REVIEW

**Comment by vStone** [comment]
@wandenberg: Could you get this merged?

**Comment by wandenberg** [comment]
Hi @vStone thanks for the PR.
Do you think possible provide a test for the `insync?` method?
And I prefer to keep the `.gitignore` as simple as possible. Do you have any specific file that it do not cover? If not, do you mind remove this commit from the PR?

**Comment by jhooyberghs** [comment]
We've cherry picked the 2 commits in the PR since we run into the same problems( sorted arrays and config file name). Is there any change on getting this merged? I guess @myMarck has long forgotten about this :)

**Comment by wandenberg** [comment]
Merged

**Pull request closed without merging**
