### PR TITLE
Feature yum repositories

### PR DESCRIPTION
**Pull request by mcgarrigle**
Allows creation of yum repositories and configures repodata depth.

rspec clears with the new tests, hope this is ok.

Cheers,
Pete.

### CODE REVIEW

**Comment by DevOpsFu** [comment]
We're interested in this addition. Can this PR be merged in @wandenberg ?

**Comment by wandenberg** [comment]
Sorry for the delay. I did not receive the notification when the PR was opened. :/

**Comment by mpwhittaker** [comment]
Any chance we can release this to the forge also ?

**Comment by wandenberg** [comment]
Hi @mpwhittaker I was waiting for a user test these change #13 .
If you can help to test I would appreciate. (Prefer to have someone else other than me testing before launch)

**Pull request merged**
