### PR TITLE
Fixes #7 Docker repository creation

### LINKED ISSUE #7: Docker Repo Creation Errors
Getting errors when creating docker proxy repos
```
Error: Error while creating nexus3_repository docker-hub-proxy: Could not run the command due to '400' '{
  "name" : "b0a010e93737bd286ca1eb259a6cc936",
  "result" : "javax.script.ScriptException: javax.validation.ConstraintViolationException"
}'
```

```
2018-10-24 08:36:28,843-0700 INFO  [qtp391406810-8550]  admin org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl - Creating repository: docker-hub-proxy -> Configuration{repositoryName='docker-hub-proxy', recipeName='docker-proxy', attributes={proxy={remoteUrl=https://registry.hub.docker.com}, storage={strictContentTypeValidation=true, blobStoreName=default}, docker={httpPort=, v1Enabled=true, forceBasicAuth=true, httpsPort=}}}
2018-10-24 08:36:28,897-0700 WARN  [qtp391406810-8550]  admin org.sonatype.nexus.repository.config.internal.ConfigurationFacetImpl - Validation failed; 1 constraints violated:
  1) may not be null, type: class org.sonatype.nexus.repository.config.internal.ConfigurationFacetImpl$SectionWrapper, property: attributes[dockerProxy].indexType, value: null

2018-10-24 08:36:28,900-0700 ERROR [qtp391406810-8550]  admin org.sonatype.nexus.script.plugin.internal.rest.ScriptResource - Exception in script execution for script named: b0a010e93737bd286ca1eb259a6cc936
javax.script.ScriptException: javax.script.ScriptException: javax.validation.ConstraintViolationException
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:162)
	at org.sonatype.nexus.internal.script.ScriptServiceImpl.eval(ScriptServiceImpl.java:153)
	at org.sonatype.nexus.internal.script.ScriptServiceImpl.eval(ScriptServiceImpl.java:162)
	at org.sonatype.nexus.common.script.ScriptService$eval$1.call(Unknown Source)

```

### PR DESCRIPTION
**Pull request by drudnev**
Resolves issues with docker group and proxy repository creation in nexus3 ( tested with 3.13 )

### CODE REVIEW

**Comment by drudnev** [comment]
This should resolve #7

**Comment by drudnev** [comment]
@wandenberg can you take a look?

**Comment by wandenberg** [comment]
Sure. Just give me some days. I am setting up a Vagrant machine inside the project to make easier to test. Instead of writing the unit tests checking the script, the idea is to make possible do "integration tests" creating the real resources and checking them. Also will allow me to validate the changes faster.

**Comment by drudnev** [comment]
Sounds like a great idea , would docker-compose be easier / faster ?

**Comment by drudnev** [comment]
@wandenberg I made a docker-compose branch in my , just need the `docker-compose.yml` and `test` folder to run. 
https://github.com/drudnev/puppet-module-nexus3_rest/tree/docker_compose

**Comment by wandenberg** [comment]
@drudnev Not sure what option will be better. Will check both :)
Here is what I have so far. https://github.com/wandenberg/puppet-module-nexus3_rest/tree/vagrant/example
It is working too, now need to work on the integration tests/refactor.
Thanks for your help. There is a good chance to use docker since it is easier to "reset" state after/between tests

**Comment by drudnev** [comment]
@wandenberg I was considering the docker-compose setup as a step towards running tests in CI like setup . travis-ci /w services. Either way actual tests against nexus API would be better than just unit tests. Let me know what you were thinking in terms of integration testing , I can give you a hand with it.

**Comment by wandenberg** [comment]
Hi @drudnev, I finally merged your request with minor changes
```
- variable names on groovy code
- renamed some properties like httpsport and forcebasicauth with underscores to be easier to read
- small fixes to read and write scripts (missing variables, using string where need symbol, ...)
- remove deletion protection for group repository, it does not cause data loss like deleting a repository
- remove list_repos.groovy, will add it when adding the docker image to have integration tests
```
Thanks a lot for your contribution and patience.

**Pull request closed without merging**
